POST /coupon/couponTemplate
Host: localhost:7020
Content-Type: application/json

{
  "policyId": 1,
  "bookId": null,
  "categoryId": null,
  "name": "생일 쿠폰",
  "amount": 0
}

###

GET /coupon/couponTemplate
Host: localhost:7020
Content-Type: application/json

###
GET /coupon/couponTemplate/2
Host: localhost:7020
Content-Type: application/json

###
GET /coupon/couponTemplate/birth
Host: localhost:7020
Content-Type: application/json

###
GET /couponTemplate/book
Host: localhost:7020
Content-Type: application/json

###
GET /couponTemplate/category
Host: localhost:7020
Content-Type: application/json

###
PUT /coupon/couponTemplate/1
Host: localhost:7020
Content-Type: application/json

{
  "policyId": 1,
  "bookId": 1,
  "categoryId": null,
  "name": "메롱 도서 쿠폰",
  "amount": 0
}

###
DELETE /couponTemplate/1
Host: localhost:7020
Content-Type: application/json

###
POST /coupon
Host: localhost:7020
Content-Type: application/json

{
  "memberId": 1,
  "couponTemplateId": 5,
  "expirationDate": "2024-02-05",
  "issueDate": "2024-02-03",
  "usedDate": null
}

###
PUT /coupon/1
Host: localhost:7020
Content-Type: application/json

###
GET /coupon/member/1
Host: localhost:7020
Content-Type: application/json

###
GET /coupon/sale?memberId=1&bookId=1&bookId=2
Host: localhost:7020
Content-Type: application/json